sudo: required
services:
  - docker

before_install:
  - docker build -t dustindavignon/docker-react -f Dockerfile.dev .

script:
 # - docker run dustindavignon/docker-react npm run test -- --coverage
  docker run -e CI=true dustindavignon/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-817531231272"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"